[build]
jobs = -1

[env]
RUST_BACKTRACE = "1"
ZYN_DEBUG = "*"
# RUST_TEST_NOCAPTURE = "1"

[net]
retry = 3

[alias]
lint = "clippy --workspace --all-features -- -D warnings"
bench-expand = "bench --bench expand"
bench-attr = "bench --bench attr"
bench-case = "bench --bench case"
bench-save = "bench -- --save-baseline main"
bench-cmp = "bench -- --baseline main"
