name: Benchmark Pull Request

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  checks: write
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: bencherdev/bencher@main

      - name: Run benchmarks
        run: |
          bencher run \
          --project zyn \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch '${{ github.head_ref }}' \
          --start-point main \
          --start-point-clone-thresholds \
          --testbed ubuntu-latest \
          --adapter rust_bench \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-upper-boundary 0.95 \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --err \
          cargo bench -p zyn
