name: Benchmarks

on:
  push:
    branches: [main]

permissions:
  contents: write
  deployments: write

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly

      - name: Run benchmarks
        run: cargo bench --workspace -- --output-format bencher 2>&1 | tee benchmarks.txt

      - name: Store results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: cargo
          output-file-path: benchmarks.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
